# https://circleci.com/docs/2.0/language-javascript/
version: 2

defaults:
  working_directory: ~/oauth-js
  docker:
    - image: circleci/node:10

jobs:
  'build':
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: npx nyc report --reporter=lcov && npx codecov
      - run: yarn run cov:check

  'deploy':
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/oauth-js
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$npm_TOKEN" > ~/oauth-js/.npmrc
      - run:
          name: Publish package
          command: yarn publish --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-latest'
