# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/oauthjs
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: npx nyc report --reporter=lcov | npx codecov
      - run: yarn run cov:check
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/oauthjs
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: npx nyc report --reporter=lcov | npx codecov
      - run: yarn cov:check

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-latest'
